/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.upc.ganado.presentacion;

import co.upc.ganado.servicios.LoginService;
import javax.swing.JOptionPane;

/**
 * Ventana de inicio de sesion del Sistema de Gestion Ganadero.
 * Valida credenciales contra el archivo data/usuarios.csv.
 *
 * @author santiago
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private final LoginService loginService;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        this.loginService = new LoginService();
        initComponents();
        
        setTitle("Sistema de Gesti\u00f3n Ganadero - Inicio de Sesi\u00f3n");
        
        //Oculta el label hasta que se ingresan los datos.
        lblAdvertencia.setVisible(false);
        
        //Al ejecutarse un evento, la lambda 'e -> validarLogin()' crea un nuevo 'ActionListener' si no existe.
        //que se guarda en la lista de listeners por medio de 'AddActionListener'.
        //Cada 'ActionListener' tiene su método 'ActionPerformed' que puede ser sobreescrito (Polimorfismo)
        btnIngresar.addActionListener(e -> validarLogin());
        textfieldContrasena.addActionListener(e -> validarLogin());
        
        //TODO: configurar la tecla 'Enter' para que se desplace entre los campos de texto como el 'Tab'
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        textfieldUsuario = new javax.swing.JTextField();
        textfieldContrasena = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        lblAdvertencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuario.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        lblUsuario.setText("Usuario");

        lblContrasena.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        lblContrasena.setText("Contraseña");

        textfieldUsuario.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N

        textfieldContrasena.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        textfieldContrasena.addActionListener(this::textfieldContrasenaActionPerformed);

        btnIngresar.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        btnIngresar.setText("Ingresar");

        lblAdvertencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdvertencia.setText("  ");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(lblContrasena, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(53, 53, 53)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textfieldUsuario)
                            .addComponent(textfieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAdvertencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuario)
                    .addComponent(textfieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContrasena)
                    .addComponent(textfieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblAdvertencia)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //No hace nada, está de adorno. No lo di pa eliminar.
    private void textfieldContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldContrasenaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblAdvertencia;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField textfieldContrasena;
    private javax.swing.JTextField textfieldUsuario;
    // End of variables declaration//GEN-END:variables

    /**
     * Valida las credenciales ingresadas contra LoginService.
     * Muestra mensajes de exito o error segun corresponda.
     */
    private void validarLogin() {
        //Extraer el texto ingresado.
        String usuario = textfieldUsuario.getText().trim(); //'.trim()' elimina los espacios.
        String contrasena = textfieldContrasena.getText().trim();

        //Validar si llenaron todos los campos.
        if (usuario.isEmpty() || contrasena.isEmpty()) {
            lblAdvertencia.setText("Debe ingresar usuario y contrase\u00f1a.");
            lblAdvertencia.setVisible(true);
            return;
        }
        
        
        //Validar si los datos son correctos.
        if (loginService.validar(usuario, contrasena)) {
            JOptionPane.showMessageDialog(this,
                    "Inicio de sesi\u00f3n exitoso. Bienvenido " + usuario + ".",
                    "Acceso concedido", JOptionPane.INFORMATION_MESSAGE); //'JOptionPane.INFORMATION_MESSAGE' solo es el ícono.
            // Aqu\u00ed se abrir\u00e1 el MainFrame cuando est\u00e9 implementado
            // new MainFrame().setVisible(true);
            dispose();
        } else {
            lblAdvertencia.setText("Usuario o contrase\u00f1a incorrectos.");
            lblAdvertencia.setVisible(true);
            textfieldContrasena.setText(""); //Limpia el campo.
            textfieldContrasena.requestFocus();
        }
    }
}
