
package co.upc.ganado.presentacion;

import co.upc.ganado.servicios.*;
import java.awt.Component;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author santiago
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private static LoginFrame login;
    
    //Para obtener la info para los páneles.
    private FincaService fincaServicio;
    private GanadoService ganadoServicio;
    private HembraService hembraServicio;
    private TrasladoService trasladoServicio;
    private PalpacionService palpacionServicio;
    private VacunaService vacunaServicio;
    private CompraService compraServicio;
    private MachoService machoServicio;
    
    private JTable tabla;
    private DefaultTableModel modeloTabla;
    

    /**
     * Creates new form MainFrame
     */
    public MainFrame(LoginFrame login) {
        this.login = login;
        
        //Crear servicios
        ganadoServicio = new GanadoService();
        fincaServicio = new FincaService(ganadoServicio);
        hembraServicio = new HembraService();
        trasladoServicio = new TrasladoService(new DetalleTrasladoService(), ganadoServicio, fincaServicio);
        palpacionServicio = new PalpacionService(new ResultadoPalpacionService(), ganadoServicio);
        vacunaServicio = new VacunaService(new AplicacionVacunaService(), ganadoServicio);
        compraServicio = new CompraService(new DetalleCompraService(), ganadoServicio);
        machoServicio = new MachoService();
        
        initComponents();
        
        //Título de la ventana.
        setTitle("sistema de Gestion Ganadero");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainFramePanel = new javax.swing.JPanel();
        btnPanelFinca = new javax.swing.JButton();
        btnPanelGanado = new javax.swing.JButton();
        btnPanelMachos = new javax.swing.JButton();
        btnPanelHembras = new javax.swing.JButton();
        btnPanelCompras = new javax.swing.JButton();
        btnPanelVentas = new javax.swing.JButton();
        btnPanelTraslados = new javax.swing.JButton();
        btnPanelPalpaciones = new javax.swing.JButton();
        btnPanelVacunas = new javax.swing.JButton();
        btnPanelConsultas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpCRUD = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        btnPanelFinca.setText("Fincas");
        btnPanelFinca.addActionListener(this::btnPanelFincaActionPerformed);

        btnPanelGanado.setText("Ganado");

        btnPanelMachos.setText("Machos");

        btnPanelHembras.setText("Hembras");
        btnPanelHembras.addActionListener(this::btnPanelHembrasActionPerformed);

        btnPanelCompras.setText("Compras");

        btnPanelVentas.setText("Ventas");

        btnPanelTraslados.setText("Traslados");

        btnPanelPalpaciones.setText("Palpaciones");

        btnPanelVacunas.setText("Vacunas");

        btnPanelConsultas.setText("Consultas");
        btnPanelConsultas.addActionListener(this::btnPanelConsultasActionPerformed);

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        javax.swing.GroupLayout mainFramePanelLayout = new javax.swing.GroupLayout(mainFramePanel);
        mainFramePanel.setLayout(mainFramePanelLayout);
        mainFramePanelLayout.setHorizontalGroup(
            mainFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFramePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(mainFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPanelCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPanelHembras, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPanelFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPanelMachos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPanelGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPanelVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPanelTraslados, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPanelVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnPanelConsultas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPanelPalpaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                .addGap(0, 56, Short.MAX_VALUE))
        );
        mainFramePanelLayout.setVerticalGroup(
            mainFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFramePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnPanelFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnPanelHembras, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnPanelMachos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPanelGanado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnPanelCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPanelVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPanelTraslados, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPanelVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPanelPalpaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPanelConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jScrollPane1.setViewportView(mainFramePanel);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout jpCRUDLayout = new javax.swing.GroupLayout(jpCRUD);
        jpCRUD.setLayout(jpCRUDLayout);
        jpCRUDLayout.setHorizontalGroup(
            jpCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCRUDLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jpCRUDLayout.setVerticalGroup(
            jpCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCRUDLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jpCRUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose(); //Cierra el MainFrame'.
        
        login.setVisible(true); //Abre el login.
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnPanelHembrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelHembrasActionPerformed
        int indicePestaña = jTabbedPane1.indexOfTab("Hembras");
        
        if (indicePestaña == -1) {
            jTabbedPane1.addTab("Hembras", new HembraPanel(hembraServicio));
        }
        
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Hembras"));
    }//GEN-LAST:event_btnPanelHembrasActionPerformed

    private void btnPanelFincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelFincaActionPerformed
        //Verificar si el tab/Pestaña ya existe en el JTabbedPane
        int indicePestaña = jTabbedPane1.indexOfTab("Finca"); //Obtine la posición de la pestaña según el título de la misma (0...n).
        
        if (indicePestaña == -1) {
            //La pestaña no existe. Toca crear una nueva instancia del panel y añadirla al JTabbedPane.
            jTabbedPane1.addTab("Finca", new FincaPanel(fincaServicio));

        }
        
        //Si ya existía la pestaña o se acaba de crear, mostrarla en pantalla.
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Finca"));
    }//GEN-LAST:event_btnPanelFincaActionPerformed

    
    
    
    //****************************************************************************************
    
    
    
    
    
    //Para añadir nuevos registros a la tabla.
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        //Obtener componente activo de JTabbedPane (el que se muestra en pantalla)
        Component componenteACtivo = jTabbedPane1.getSelectedComponent();
        
        //Validar si el componente es una instancia de algún panel.
        if (componenteACtivo instanceof FincaPanel) {
            ((FincaPanel) componenteACtivo).nuevo();
        } else if (componenteACtivo instanceof HembraPanel) {
            ((HembraPanel) componenteACtivo).nuevo();
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    
    //Para editar registros de las tablas.
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //Obtener componente activo de JTabbedPane (el que se muestra en pantalla)
        Component componenteACtivo = jTabbedPane1.getSelectedComponent();
        
        //Validar si el componente es una instancia de algún panel.
        if (componenteACtivo instanceof FincaPanel) {
            ((FincaPanel) componenteACtivo).editar();
        } else if (componenteACtivo instanceof HembraPanel) {
            ((HembraPanel) componenteACtivo).editar();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Component componenteACtivo = jTabbedPane1.getSelectedComponent();

        if (componenteACtivo instanceof FincaPanel) {
            ((FincaPanel) componenteACtivo).eliminar();
        } else if (componenteACtivo instanceof HembraPanel) {
            ((HembraPanel) componenteACtivo).eliminar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnPanelConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelConsultasActionPerformed
        //Verificar si el tab/Pestaña ya existe en el JTabbedPane
        int indicePestaña = jTabbedPane1.indexOfTab("Consultas"); //Obtine la posición de la pestaña según el título de la misma (0...n).
        
        if (indicePestaña == -1) {
            //La pestaña no existe. Toca crear una nueva instancia del panel y añadirla al JTabbedPane.
            jTabbedPane1.addTab("Consultas", new ConsultasPanel(trasladoServicio, hembraServicio, palpacionServicio, vacunaServicio, fincaServicio, compraServicio, machoServicio));

        }
        
        //Si ya existía la pestaña o se acaba de crear, mostrarla en pantalla.
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Consultas"));
    }//GEN-LAST:event_btnPanelConsultasActionPerformed
    
    
    

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPanelCompras;
    private javax.swing.JButton btnPanelConsultas;
    private javax.swing.JButton btnPanelFinca;
    private javax.swing.JButton btnPanelGanado;
    private javax.swing.JButton btnPanelHembras;
    private javax.swing.JButton btnPanelMachos;
    private javax.swing.JButton btnPanelPalpaciones;
    private javax.swing.JButton btnPanelTraslados;
    private javax.swing.JButton btnPanelVacunas;
    private javax.swing.JButton btnPanelVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpCRUD;
    private javax.swing.JPanel mainFramePanel;
    // End of variables declaration//GEN-END:variables
}
